apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: microshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-readonly
  namespace: microshop
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-readonly-binding
  namespace: microshop
subjects:
  - kind: ServiceAccount
    name: api-sa
    namespace: microshop
roleRef:
  kind: Role
  name: api-readonly
  apiGroup: rbac.authorization.k8s.io
